### ISSUE TITLE
SequelizeValidationError when adding MessageButton to MessageActionRow

### ISSUE THREAD

**Issue by TimmyRB** [AngeloCore/discord-buttons#103]
```
Discord-Buttons: v3.2.1
Discord.js @ master
```

When I try to add a MessageButton or multiple MessageButtons to a MessageActionRow in any way (via `.addComponent(button)` or `.addComponents(buttons)` or thru the constructor `({ components: buttons })`) I always receive the same error seen below, this error doesn't appear if I comment out the line adding to the MessageActionRow

```
(node:4356) UnhandledPromiseRejectionWarning: SequelizeValidationError: string violation: result cannot be an array or an object
    at InstanceValidator._validate (/Users/jnbra/Projects/SydneyBot/node_modules/sequelize/lib/instance-validator.js:78:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InstanceValidator._validateAndRunHooks (/Users/jnbra/Projects/SydneyBot/node_modules/sequelize/lib/instance-validator.js:111:7)
    at InstanceValidator.validate (/Users/jnbra/Projects/SydneyBot/node_modules/sequelize/lib/instance-validator.js:93:12)
    at Logs.save (/Users/jnbra/Projects/SydneyBot/node_modules/sequelize/lib/model.js:3877:7)
    at Function.create (/Users/jnbra/Projects/SydneyBot/node_modules/sequelize/lib/model.js:2207:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not sure if it's an incompatibly with Sequelize but I know for sure it only happens when adding a MessageButton to a MessageActionRow. Any help figuring this out would be greatly appreciated!

**Comment by Madnesssik** [comment]
Hey, can u provide your command code?

**Comment by TimmyRB** [comment]
I assume you mean this?
```ts
let embed: MessageEmbed = new MessageEmbed({
    title: this.data?.title,
    description: this.data?.description
})

let buttons: MessageButton[] = [];
for (let r of this.data?.reactionRoles!) {
    buttons.push(new MessageButton({ style: 'SECONDARY', customID: r.roleId, label: r.name, emoji: r.emoji }))
}

console.dir(buttons)

let row = new MessageActionRow({ components: buttons });

// Never reaches this because of the line above
console.dir(row)

interaction.editReply({ embeds: [embed], components: [row] }).then(msg => {
    Database.createAssigner(msg.id, interaction.user.id, this.data?.title!, this.data?.description!, this.data?.reactionRoles!)
}).catch(err => console.error(err))
```

**Comment by Madnesssik** [comment]
oh okay soo 

This:

```js
let row = new MessageActionRow({ components: buttons });
```

Shoud look like this:

```js
let row = new MessageActionRow()
     .addComponent(button)
```

**Comment by TimmyRB** [comment]
It doesn't matter how I add the Button to the row or if I add one or multiple, it always returns the same error.

**Comment by Madnesssik** [comment]
Ohh, so okay this error is based on your database. This error is as a result of submitting a value of a wrong type compared to the one declared in the model.

**Comment by TimmyRB** [comment]
If I comment out the database code I still get this error, it's only when I comment out the function adding to the row that I don't get the error message, I'm also never passing the row or buttons into the database

**Comment by Madnesssik** [comment]
@TimmyRB I worked in your code and i figured out that you try to use `"SECONDARY"` style that doesn't exist. After some try's and changing 

```js
const Discord = require('discord.js')
const disbut = require('discord-buttons')

let embed = new Discord.MessageEmbed({
    title: "title",
    description: "description"
})

let buttons = new disbut.MessageButton()
.setStyle('red')
.setID('id')
.setLabel('label')

let row = new disbut.MessageActionRow({ component: buttons });

// Never reaches this because of the line above
console.log(row)
```

This code works fine for me and results are

Output:
```
MessageActionRow {
  type: 1,
  components: [
    MessageButton {
      type: 2,
      style: 4,
      label: 'label',
      disabled: false,
      emoji: undefined,
      url: undefined,
      custom_id: 'id'
    }
  ]
}```

**Comment by TimmyRB** [comment]
Ahh turns out Discord.js already has integration for Bot Buttons and I thought I was trying to assign a MessageButton imported from Discord.js to a MessageActionRow imported from discord-buttons which caused the error, I just removed discord-buttons and switched to Discord.js entirely and everything works now. Thanks!
