### ISSUE TITLE
throw new TypeError('CLIENT_MISSING_INTENTS');

### ISSUE THREAD

**Issue by kingofsponges** [AngeloCore/discord-buttons#28]
for some reason when i just try to run the bot it comes up with this:
```
path to my bot\node_modules\discord.js\src\client\Client.js:454
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (path to my bot\node_modules\discord.js\src\client\Client.js:454:13)
    at new Client (path to my bot\node_modules\discord.js\src\client\Client.js:75:10)
    at Object.<anonymous> (path to my bot\bot.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}
```
when i do anything without using discord-buttons, it just works. but when i do anything with it, my bot literally crashes for an unknown reason

**Comment by xHyroM** [comment]
You need provide intents like:
```js
new Client({intents: Discord.Intents.ALL})
```

**Comment by kingofsponges** [comment]
alright that'll work well, it no longer shows me that error

now i'll only find a way to CORRECTLY use this package
