### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Crni39** [AngeloCore/discord-buttons#5]
```javascript
Error: Cannot find module './Events/INTERACTION_CREATE'
Require stack:
- /home/container/node_modules/discord-buttons/src/index.js
- /home/container/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/home/container/node_modules/discord-buttons/src/index.js:6:28)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/container/node_modules/discord-buttons/src/index.js',
'/home/container/index.js'```

**Comment by Crni39** [comment]
Add /src

**Comment by Crni39** [comment]
How to fix:
1. Rename `INTERACTION_CREATE.JS` to `INTERACTION_CREATE.js`
2. Add .js: const INTERACTION_CREATE = require('./Events/INTERACTION_CREATE.js');

**Comment by AngeloCore** [comment]
Yes, i will fix on the next version
