### ISSUE TITLE
TypeError: NO_BUTTON_TYPE: Invalid type

### ISSUE THREAD

**Issue by thebigwolfy** [AngeloCore/discord-buttons#60]
I have a error (i am french)
```
(node:44) UnhandledPromiseRejectionWarning: TypeError: NO_BUTTON_TYPE: Invalid type
at Object.resolveButton (/home/container/node_modules/discord-buttons/src/v12/Util.js:25:55)
at APIMessage.resolveData (/home/container/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:90:63)
at TextChannel.send (/home/container/node_modules/discord-buttons/src/v12/Classes/TextChannel.js:18:68)
at Object.module.exports.run (/home/container/bot/commands/test.js:30:19)
at Query.onResult (/home/container/bot/events/message.js:111:16)
at /home/container/node_modules/mysql2/lib/commands/query.js:72:16
at processTicksAndRejections (internal/process/task_queues.js:79:11)
at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
at processPromiseRejections (internal/process/promises.js:211:11)
at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by TsWin** [comment]
I think your .setType() is invalid
Check [this](https://discord-buttons.js.org/examples) link to find all different type of styles

**Comment by gaetan20** [comment]
> I have a error (i am french)
> 
> ```
> (node:44) UnhandledPromiseRejectionWarning: TypeError: NO_BUTTON_TYPE: Invalid type
> at Object.resolveButton (/home/container/node_modules/discord-buttons/src/v12/Util.js:25:55)
> at APIMessage.resolveData (/home/container/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:90:63)
> at TextChannel.send (/home/container/node_modules/discord-buttons/src/v12/Classes/TextChannel.js:18:68)
> at Object.module.exports.run (/home/container/bot/commands/test.js:30:19)
> at Query.onResult (/home/container/bot/events/message.js:111:16)
> at /home/container/node_modules/mysql2/lib/commands/query.js:72:16
> at processTicksAndRejections (internal/process/task_queues.js:79:11)
> at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
> at processPromiseRejections (internal/process/promises.js:211:11)
> at processTicksAndRejections (internal/process/task_queues.js:98:32)
> ```

ask for support on SRC server

**Comment by thebigwolfy** [comment]
> I think your .setType() is invalid
> Check [this](https://discord-buttons.js.org/examples) link to find all different type of styles

The message is not have the buttons !

**Comment by AngeloCore** [comment]
give your full code, please

**Comment by thebigwolfy** [comment]
Fixed bug for sorry !
