### ISSUE TITLE
resolveString is not a function

### ISSUE THREAD

**Issue by TurtlePaw** [AngeloCore/discord-buttons#68]
I am using the following with discord-buttons.
The code works in Win 10 with WSL/Ubuntu but on a Ubuntu virtual machine, I get the following error

```
(node:225042) UnhandledPromiseRejectionWarning: TypeError: resolveString is not a function
    at MessageButton.setStyle (/home/ubuntu/bottwo/node_modules/discord-buttons/src/Classes/MessageButton.js:30:30)
    at Object.execute (/home/ubuntu/bottwo/cmds/Dev/-.js:11:8)
    at Client.<anonymous> (/home/ubuntu/bottwo/index.js:352:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
```

I have rebuild my node_modules on both boxes.
My code is the following

```js
    let btn = new message.client.disbut.MessageButton()
      .setStyle('blurple')
      .setLabel(`Buttons!! 🎉`)
      .setID('stupiddm');
      const bt = new Discord.MessageEmbed()
      .setTitle(`Buttons!! 🎉`)
      .setColor(message.client.confiig.color)
    let msg = await message.channel.send({
      button: btn,
      embed: bt
    });
```    

and this is my package.json
```json
  "dependencies": {
    "canvacord": "^5.2.0",
    "canvas": "^2.8.0",
    "common-tags": "^1.8.0",
    "discord-buttons": "^2.4.1",
    "discord-xp": "^1.1.14",
    "discord.js": "github:discordjs/discord.js",
    "dog-img": "^1.0.1",
    "generate-password": "^1.6.0",
    "key-file-storage": "^2.2.9",
    "klaw-sync": "^6.0.0",
    "mongoose": "^5.12.10",
    "ms": "^2.1.3",
    "node-fetch": "^2.6.1",
    "random": "^3.0.6",
    "random-animals-api": "^1.2.6",
    "random-email": "^1.0.3",
    "uuid": "^8.3.2"
  }
  ```

**Comment by es183923** [comment]
What is your node.js version? It's possible that your node version up to date enough. Also, try running with the `--trace-warnings` flag.

**Comment by es183923** [comment]
Try updating `discord-buttons` as well. The latest version is `3.1.1`.

**Comment by TurtlePaw** [comment]
> What is your node.js version? It's possible that your node version up to date enough. Also, try running with the `--trace-warnings` flag.

The new discord.js version was not working... I'm using the old version

**Comment by EhsanFox** [comment]
we only support djs v12+ and you need to have at least Nodejs 12.x
